const METAMASK_CONNECT = 'METAMASK_CONNECT';
const METAMASK_CONNECT_SUCCESS = 'METAMASK_CONNECT_SUCCESS';
const METAMASK_CONNECT_FAILURE = 'METAMASK_CONNECT_FAILURE';

export {METAMASK_CONNECT,METAMASK_CONNECT_SUCCESS,METAMASK_CONNECT_FAILURE};
