const USER_FIND ='USER_FIND';
const USER_FIND_SUCCESS = 'USER_FIND_SUCCESS';
const USER_FIND_FAILURE =  'USER_FIND_FAILURE';
const USER_CONNECT = 'USER_CONNECT';
const USER_CONNECT_SUCCESS = 'USER_CONNECT_SUCCESS';
const USER_CONNECT_FAILURE = 'USER_CONNECT_FAILURE';
const USER_LOGOUT = 'USER_LOGOUT';
const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export {
		USER_FIND,
		USER_FIND_SUCCESS,
		USER_FIND_FAILURE,
		USER_CONNECT,
		USER_CONNECT_SUCCESS,
		USER_CONNECT_FAILURE,
		USER_LOGOUT,
		USER_LOGOUT_SUCCESS,
		USER_LOGOUT_FAILURE
	};
